import { useState } from 'react'
import { aiApi } from '@/utils/api'

const RASHIS = [
  {n:'Mesha',e:'Aries',s:'♈'},{n:'Vrishabha',e:'Taurus',s:'♉'},{n:'Mithuna',e:'Gemini',s:'♊'},
  {n:'Karka',e:'Cancer',s:'♋'},{n:'Simha',e:'Leo',s:'♌'},{n:'Kanya',e:'Virgo',s:'♍'},
  {n:'Tula',e:'Libra',s:'♎'},{n:'Vrischika',e:'Scorpio',s:'♏'},{n:'Dhanu',e:'Sagittarius',s:'♐'},
  {n:'Makara',e:'Capricorn',s:'♑'},{n:'Kumbha',e:'Aquarius',s:'♒'},{n:'Meena',e:'Pisces',s:'♓'},
]
const PERIODS = ['daily','weekly','monthly','yearly']

export default function HoroscopePage() {
  const [sel, setSel] = useState(RASHIS[4])
  const [period, setPeriod] = useState('daily')
  const [loading, setLoading] = useState(false)
  const [reading, setReading] = useState<any>(null)
  const [error, setError] = useState('')

  const fetchHoroscope = async (rashi = sel, p = period) => {
    setLoading(true); setError(''); setReading(null)
    try {
      const res = await aiApi.horoscope({ rashi: rashi.n, rashi_english: rashi.e, period_type: p })
      setReading(res.data.reading)
    } catch (e: any) {
      setError('AI service unavailable. Please add your ANTHROPIC_API_KEY in backend .env file.')
    } finally { setLoading(false) }
  }

  const ScoreBar = ({label, val, color}: {label:string, val:number, color:string}) => (
    <div className="score-bar-wrap">
      <div className="score-label-row">
        <span className="score-label-text">{label}</span>
        <span className="score-label-text">{val}%</span>
      </div>
      <div className="score-track">
        <div className="score-fill" style={{width:`${val}%`, background:color}} />
      </div>
    </div>
  )

  return (
    <div>
      <div className="section-title">☽ AI-Powered Daily Horoscope</div>
      <p style={{color:'var(--cream-muted)',fontStyle:'italic',fontSize:'0.9rem',marginBottom:'1.25rem'}}>
        ✨ Personalized readings generated by Claude AI, powered by authentic Vedic astrology
      </p>

      {/* Period selector */}
      <div className="flex-wrap mb-md">
        {PERIODS.map(p => (
          <button key={p} onClick={() => setPeriod(p)} className={`btn-filter${period===p?' active':''}`}>
            {p.toUpperCase()}
          </button>
        ))}
      </div>

      {/* Rashi grid */}
      <div style={{display:'grid', gridTemplateColumns:'repeat(6, 1fr)', gap:'6px', marginBottom:'1.5rem'}}>
        {RASHIS.map(r => (
          <button key={r.n} onClick={() => setSel(r)} className={`btn-sign${sel.n===r.n?' active':''}`}>
            <span className="sym">{r.s}</span>
            <span className="lbl">{r.e}</span>
          </button>
        ))}
      </div>

      {/* Generate button */}
      <div style={{textAlign:'center', marginBottom:'2rem'}}>
        <button onClick={() => fetchHoroscope()} disabled={loading} className="btn-gold">
          {loading ? '🔮 Consulting the Stars...' : `✦ Generate ${period.charAt(0).toUpperCase()+period.slice(1)} Reading for ${sel.n} ✦`}
        </button>
      </div>

      {/* Error */}
      {error && (
        <div style={{background:'rgba(201,107,138,0.1)', border:'1px solid rgba(201,107,138,0.35)',
          borderRadius:'3px', padding:'1.25rem', marginBottom:'1.5rem', color:'var(--rose)'}}>
          ⚠ {error}
        </div>
      )}

      {/* Loading shimmer */}
      {loading && (
        <div className="card card-p-lg" style={{textAlign:'center', padding:'4rem'}}>
          <div style={{fontSize:'3rem', marginBottom:'1rem', animation:'pulseGold 2s ease-in-out infinite'}}>🔮</div>
          <p style={{fontFamily:'var(--font-heading)', color:'var(--gold)', letterSpacing:'0.15em', fontSize:'0.85rem'}}>
            CONSULTING THE COSMIC ARCHIVES
          </p>
          <p style={{color:'var(--cream-muted)', fontStyle:'italic', marginTop:'0.5rem', fontSize:'0.9rem'}}>
            Claude AI is channeling ancient Vedic wisdom for {sel.n}...
          </p>
        </div>
      )}

      {/* AI Reading */}
      {reading && !loading && (
        <div className="page-enter" style={{display:'flex', flexDirection:'column', gap:'1.25rem'}}>
          {/* Header */}
          <div className="card card-p-lg">
            <div className="horo-sign-header">
              <span className="horo-sign-symbol">{sel.s}</span>
              <div>
                <div className="horo-sign-name">{sel.n}</div>
                <div className="horo-sign-date">{sel.e} · {period.charAt(0).toUpperCase()+period.slice(1)} Reading</div>
                <div style={{marginTop:'6px'}}>
                  <span className="badge">✨ AI Generated</span>
                  <span className="badge" style={{marginLeft:'6px'}}>🪐 Vedic</span>
                </div>
              </div>
            </div>

            {/* Scores */}
            <div className="grid-4" style={{marginBottom:'1.25rem'}}>
              <ScoreBar label="Love" val={reading.love_score||75} color="#e91e63" />
              <ScoreBar label="Career" val={reading.career_score||80} color="#f39c12" />
              <ScoreBar label="Health" val={reading.health_score||72} color="#2ecc71" />
              <ScoreBar label="Finance" val={reading.finance_score||78} color="#3498db" />
            </div>

            {/* Main prediction */}
            <p style={{fontSize:'1.05rem', lineHeight:'1.9', color:'var(--cream)', marginBottom:'0'}}>{reading.main_prediction}</p>
          </div>

          {/* Life areas */}
          <div className="grid-3">
            {[
              ['♥ Love & Relationships', reading.love, '#e91e63'],
              ['✦ Career & Finance', reading.career, '#c9a84c'],
              ['✿ Health & Wellness', reading.health, '#2ecc71'],
            ].map(([lbl, txt, col]) => (
              <div className="card card-p" key={lbl}>
                <div style={{fontFamily:'var(--font-heading)', fontSize:'0.72rem', letterSpacing:'0.1em',
                  color:col as string, marginBottom:'0.6rem'}}>{lbl}</div>
                <p style={{color:'var(--cream-dim)', fontSize:'0.9rem', lineHeight:'1.7'}}>{txt}</p>
              </div>
            ))}
          </div>

          {/* Spiritual + Remedy */}
          <div className="grid-2">
            {reading.spiritual && (
              <div className="card card-p">
                <div style={{fontFamily:'var(--font-heading)', fontSize:'0.72rem', letterSpacing:'0.1em', color:'var(--gold-light)', marginBottom:'0.6rem'}}>🕉 Spiritual Guidance</div>
                <p style={{color:'var(--cream-dim)', fontSize:'0.9rem', lineHeight:'1.7'}}>{reading.spiritual}</p>
              </div>
            )}
            {reading.remedy && (
              <div className="card card-p">
                <div style={{fontFamily:'var(--font-heading)', fontSize:'0.72rem', letterSpacing:'0.1em', color:'var(--gold-light)', marginBottom:'0.6rem'}}>✿ Remedy of the Day</div>
                <p style={{color:'var(--cream-dim)', fontSize:'0.9rem', lineHeight:'1.7', marginBottom:'0.6rem'}}>{reading.remedy}</p>
                {reading.mantra && <p style={{fontStyle:'italic', color:'rgba(201,168,76,0.7)', fontSize:'0.82rem', borderLeft:'2px solid rgba(201,168,76,0.3)', paddingLeft:'0.75rem'}}>{reading.mantra}</p>}
              </div>
            )}
          </div>

          {/* Lucky */}
          <div className="card card-p">
            <div style={{fontFamily:'var(--font-heading)', color:'var(--gold-light)', fontSize:'0.72rem', letterSpacing:'0.15em', marginBottom:'1rem'}}>LUCKY ELEMENTS</div>
            <div className="lucky-row" style={{paddingTop:0, borderTop:'none'}}>
              {[['COLOR',reading.lucky_color],['NUMBER',reading.lucky_number],
                ['GEM',reading.lucky_gem],['BEST DAY',reading.lucky_day]].map(([k,v])=>(
                <div className="lucky-item" key={k}>
                  <div className="lucky-key">{k}</div>
                  <div className="lucky-val">{v}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Empty state */}
      {!reading && !loading && !error && (
        <div style={{textAlign:'center', padding:'4rem 2rem', color:'var(--cream-muted)'}}>
          <div style={{fontSize:'4rem', marginBottom:'1rem', opacity:0.4}}>☽</div>
          <p style={{fontStyle:'italic'}}>Select your rashi and click Generate to receive your AI-powered cosmic reading</p>
        </div>
      )}
    </div>
  )
}
